//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exchaup.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("exchaup.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        internal static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        internal static string Label_EnterConfirmPassword {
            get {
                return ResourceManager.GetString("Label_EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        internal static string Label_EnterEmailOrPhone {
            get {
                return ResourceManager.GetString("Label_EnterEmailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        internal static string Label_EnterYourName {
            get {
                return ResourceManager.GetString("Label_EnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string Label_EnterYourPassword {
            get {
                return ResourceManager.GetString("Label_EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string Label_ForgotPassword {
            get {
                return ResourceManager.GetString("Label_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate code.
        /// </summary>
        internal static string Label_GenerateCode {
            get {
                return ResourceManager.GetString("Label_GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered invalid email address or password, please correct and try again..
        /// </summary>
        internal static string Label_InvalidCrentials {
            get {
                return ResourceManager.GetString("Label_InvalidCrentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new account.
        /// </summary>
        internal static string Label_RegisterNewAccount {
            get {
                return ResourceManager.GetString("Label_RegisterNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string Label_ResetPassword {
            get {
                return ResourceManager.GetString("Label_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code:.
        /// </summary>
        internal static string Label_SecurityCode {
            get {
                return ResourceManager.GetString("Label_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code sent on your email address.
        /// </summary>
        internal static string Label_SecurityCodeSent {
            get {
                return ResourceManager.GetString("Label_SecurityCodeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email:.
        /// </summary>
        internal static string Label_YourEmailOrPhone {
            get {
                return ResourceManager.GetString("Label_YourEmailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name:.
        /// </summary>
        internal static string Label_YourName {
            get {
                return ResourceManager.GetString("Label_YourName", resourceCulture);
            }
        }
    }
}
